practica1: objetos source/practica1_objetos.cc
	g++ -o practica1_objetos source/practica1_objetos.cc object/objetos.o -lglut -lGLU -lGL -lm -I include
objetos: source/objetos.cc include/vertex.h include/objetos.h
	g++ -c -o object/objetos.o source/objetos.cc -I include


